baseurl = "https://frontop.github.io/"
languageCode = "en-us"
title = "Frontop Engineering"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Work"
    url = "/work"
  [[menu.header]]
    weight = 4
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "/contact"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Frontop Engineering"
    subtitle = "Be in the front, to provide top service"

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Established in 2005"
    paragraph = "Frontop has been consistently providing top quality service for over a decade, and is now one of the top engineering consulting firms in Ontario. We focus on geotechnical instrumentation and monitoring, with over 50 employees including Professional Engineers, Instrumentation and Monitoring specialists, Software Engineers and Noise and Vibration experts."

  [params.blog]
    enable = false
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Providing geotechnical engineering services in Ontario, Canada"
    content = "Frontop provides multiple engineering services including: geotechnical instrumentation and monitoring, real-time noise and vibration monitoring, computer science and software developing engineering, precision surveying and construction layout, geotechnical engineering, as well as structural, civil work, electrical and mechanical (HVAC, plumbing and fire protection) design. We incorporate our wide range of knowledge and experience to ensure works of excellence and high quality, guaranteeing that the needs of our clients are satisfied.."
    [params.feature.button]
      caption = "View Projects"
      url = "/work"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "For any inquiries, questions or commendations, please get in touch!"
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "101 Amber Street, Unit 1, Markham, ON L3R 3B2"
      email = "Email: info@frontop.ca"
      phone = "Phone: (905) 947-0900"
    [params.contact.gmaps]
      title = "Directions to our office"
